global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:80"]

  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:80"]

  - job_name: "product-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:80"]

  - job_name: "order-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:80"]
